// content/docs/children-slots/ProfileCard.vue
<script setup lang="ts">
defineProps<{ title: string }>();
</script>

<template>
  <section class="demo-card">
    <span class="demo-tag">default / footer slot</span>
    <h2>{{ title }}</h2>
    <div><slot /></div>
    <div class="demo-actions"><slot name="footer" /></div>
  </section>
</template>

// content/docs/children-slots/ProfileCard.tsx
import type { ReactNode } from "react";

type ProfileCardProps = {
  children: ReactNode;
  footer: ReactNode;
  title: string;
};

export function ProfileCard({ children, footer, title }: ProfileCardProps) {
  return (
    <section className="demo-card">
      <span className="demo-tag">children / footer prop</span>
      <h2>{title}</h2>
      <div>{children}</div>
      <div className="demo-actions">{footer}</div>
    </section>
  );
}
